"""
Property-based tests for compliance report structure
Feature: rag-compliance-engine
"""
import sys
import os

# Add parent directory to path for imports
sys.path.insert(0, os.path.join(os.path.dirname(__file__), '..'))

from hypothesis import given, strategies as st, settings
from app.compliance import ComplianceAuditor
from app.schemas import InvoiceData, ExpenseCategory
from unittest.mock import Mock, patch, MagicMock
import json


# Strategy for generating invoice data
def invoice_strategy():
    """Generate random invoice data for testing."""
    return st.builds(
        InvoiceData,
        vendor_name=st.text(min_size=1, max_size=100),
        invoice_number=st.one_of(st.none(), st.text(min_size=1, max_size=50)),
        date=st.one_of(st.none(), st.text(min_size=1, max_size=20)),
        total_amount=st.floats(min_value=0.01, max_value=1000000, allow_nan=False, allow_infinity=False),
        tax_amount=st.floats(min_value=0.0, max_value=100000, allow_nan=False, allow_infinity=False),
        gstin=st.one_of(
            st.none(),
            st.text(min_size=15, max_size=15)
        ),
        currency=st.just("INR"),
        category=st.sampled_from(ExpenseCategory),
        item_description=st.text(min_size=1, max_size=200)
    )


# Feature: rag-compliance-engine, Property 15: Compliance Report Structure
@given(invoice=invoice_strategy())
@settings(max_examples=100, deadline=None)
def test_compliance_report_has_required_keys(invoice):
    """
    Property 15: Compliance Report Structure
    
    For any compliance report generated by the auditor, the report SHALL
    contain all required keys: status, flags (as a list), category, and 
    citations (as a list).
    
    Validates: Requirements 9.8
    """
    # Mock environment variables
    with patch.dict(os.environ, {
        'GOOGLE_API_KEY': 'test-api-key',
        'CONVEX_URL': 'https://test.convex.cloud'
    }):
        # Mock ConvexClient
        with patch('app.compliance.ConvexClient') as mock_convex_class:
            mock_convex = MagicMock()
            mock_convex_class.return_value = mock_convex
            
            # Mock vector search results
            mock_convex.query.return_value = [
                {
                    "chunk_text": "Sample legal text about GST compliance",
                    "source_file": "a2017-12.pdf",
                    "page_number": 42,
                    "category": "GST",
                    "score": 0.85
                }
            ]
            
            # Mock Gemini API Client for embeddings
            with patch('app.rag_query.genai.Client') as mock_client_class:
                mock_client = MagicMock()
                mock_embed_result = Mock()
                mock_embed_result.embeddings = [Mock(values=[0.1] * 768)]
                mock_client.models.embed_content.return_value = mock_embed_result
                mock_client_class.return_value = mock_client
                
                # Mock Gemini API Client for AI analysis
                with patch('app.rag_analyzer.genai.Client') as mock_ai_client_class:
                    mock_ai_client = MagicMock()
                    mock_response = Mock()
                    mock_response.text = json.dumps({
                        "status": "compliant",
                        "flags": ["AI analysis flag"],
                        "itc_eligible": True,
                        "reasoning": "Test reasoning"
                    })
                    mock_ai_client.models.generate_content.return_value = mock_response
                    mock_ai_client_class.return_value = mock_ai_client
                    
                    # Create auditor and run audit
                    auditor = ComplianceAuditor()
                    report = auditor.audit_invoice(invoice)
    
    # Property 1: Report must be a dictionary
    assert isinstance(report, dict), (
        f"Expected report to be a dictionary.\n"
        f"Got type: {type(report)}"
    )
    
    # Property 2: Report must contain 'status' key
    assert "status" in report, (
        f"Expected report to contain 'status' key.\n"
        f"Report keys: {list(report.keys())}\n"
        f"Invoice: vendor={invoice.vendor_name}, amount={invoice.total_amount}"
    )
    
    # Property 3: Report must contain 'flags' key
    assert "flags" in report, (
        f"Expected report to contain 'flags' key.\n"
        f"Report keys: {list(report.keys())}\n"
        f"Invoice: vendor={invoice.vendor_name}, amount={invoice.total_amount}"
    )
    
    # Property 4: 'flags' must be a list
    assert isinstance(report["flags"], list), (
        f"Expected 'flags' to be a list.\n"
        f"Got type: {type(report['flags'])}\n"
        f"Invoice: vendor={invoice.vendor_name}, amount={invoice.total_amount}"
    )
    
    # Property 5: Report must contain 'category' key
    assert "category" in report, (
        f"Expected report to contain 'category' key.\n"
        f"Report keys: {list(report.keys())}\n"
        f"Invoice: vendor={invoice.vendor_name}, amount={invoice.total_amount}"
    )
    
    # Property 6: Report must contain 'citations' key
    assert "citations" in report, (
        f"Expected report to contain 'citations' key.\n"
        f"Report keys: {list(report.keys())}\n"
        f"Invoice: vendor={invoice.vendor_name}, amount={invoice.total_amount}"
    )
    
    # Property 7: 'citations' must be a list
    assert isinstance(report["citations"], list), (
        f"Expected 'citations' to be a list.\n"
        f"Got type: {type(report['citations'])}\n"
        f"Invoice: vendor={invoice.vendor_name}, amount={invoice.total_amount}"
    )


# Feature: rag-compliance-engine, Property 15: Compliance Report Structure (RAG Failure)
@given(invoice=invoice_strategy())
@settings(max_examples=100, deadline=None)
def test_compliance_report_structure_on_rag_failure(invoice):
    """
    Property 15: Compliance Report Structure (RAG Failure Case)
    
    For any compliance report generated when RAG analysis fails, the report 
    SHALL still contain all required keys with proper types, falling back to 
    hard rules validation.
    
    Validates: Requirements 9.8, 12.1, 12.2
    """
    # Mock environment variables
    with patch.dict(os.environ, {
        'GOOGLE_API_KEY': 'test-api-key',
        'CONVEX_URL': 'https://test.convex.cloud'
    }):
        # Mock ConvexClient
        with patch('app.compliance.ConvexClient') as mock_convex_class:
            mock_convex = MagicMock()
            mock_convex_class.return_value = mock_convex
            
            # Mock vector search to raise an exception (RAG failure)
            mock_convex.query.side_effect = Exception("Vector search failed")
            
            # Create auditor and run audit
            auditor = ComplianceAuditor()
            report = auditor.audit_invoice(invoice)
    
    # Property 1: Report must still be a dictionary
    assert isinstance(report, dict), (
        f"Expected report to be a dictionary even on RAG failure.\n"
        f"Got type: {type(report)}"
    )
    
    # Property 2: Report must contain all required keys
    required_keys = ["status", "flags", "category", "citations"]
    for key in required_keys:
        assert key in report, (
            f"Expected report to contain '{key}' key even on RAG failure.\n"
            f"Report keys: {list(report.keys())}\n"
            f"Invoice: vendor={invoice.vendor_name}, amount={invoice.total_amount}"
        )
    
    # Property 3: 'flags' must be a list
    assert isinstance(report["flags"], list), (
        f"Expected 'flags' to be a list even on RAG failure.\n"
        f"Got type: {type(report['flags'])}"
    )
    
    # Property 4: 'citations' must be a list (empty on RAG failure)
    assert isinstance(report["citations"], list), (
        f"Expected 'citations' to be a list even on RAG failure.\n"
        f"Got type: {type(report['citations'])}"
    )


# Feature: rag-compliance-engine, Property 15: Compliance Report Structure (Empty Search Results)
@given(invoice=invoice_strategy())
@settings(max_examples=100, deadline=None)
def test_compliance_report_structure_with_empty_search_results(invoice):
    """
    Property 15: Compliance Report Structure (Empty Search Results)
    
    For any compliance report generated when vector search returns no results,
    the report SHALL still contain all required keys with proper types.
    
    Validates: Requirements 9.8
    """
    # Mock environment variables
    with patch.dict(os.environ, {
        'GOOGLE_API_KEY': 'test-api-key',
        'CONVEX_URL': 'https://test.convex.cloud'
    }):
        # Mock ConvexClient
        with patch('app.compliance.ConvexClient') as mock_convex_class:
            mock_convex = MagicMock()
            mock_convex_class.return_value = mock_convex
            
            # Mock vector search to return empty results
            mock_convex.query.return_value = []
            
            # Mock Gemini API Client for embeddings
            with patch('app.rag_query.genai.Client') as mock_client_class:
                mock_client = MagicMock()
                mock_embed_result = Mock()
                mock_embed_result.embeddings = [Mock(values=[0.1] * 768)]
                mock_client.models.embed_content.return_value = mock_embed_result
                mock_client_class.return_value = mock_client
                
                # Create auditor and run audit
                auditor = ComplianceAuditor()
                report = auditor.audit_invoice(invoice)
    
    # Property 1: Report must be a dictionary
    assert isinstance(report, dict), (
        f"Expected report to be a dictionary with empty search results.\n"
        f"Got type: {type(report)}"
    )
    
    # Property 2: Report must contain all required keys
    required_keys = ["status", "flags", "category", "citations"]
    for key in required_keys:
        assert key in report, (
            f"Expected report to contain '{key}' key with empty search results.\n"
            f"Report keys: {list(report.keys())}"
        )
    
    # Property 3: 'flags' must be a list
    assert isinstance(report["flags"], list), (
        f"Expected 'flags' to be a list with empty search results.\n"
        f"Got type: {type(report['flags'])}"
    )
    
    # Property 4: 'citations' must be an empty list
    assert isinstance(report["citations"], list), (
        f"Expected 'citations' to be a list with empty search results.\n"
        f"Got type: {type(report['citations'])}"
    )
    assert len(report["citations"]) == 0, (
        f"Expected 'citations' to be empty when search returns no results.\n"
        f"Got {len(report['citations'])} citations"
    )


# Feature: rag-compliance-engine, Property 15: Compliance Report Structure (Category Preservation)
@given(invoice=invoice_strategy())
@settings(max_examples=100, deadline=None)
def test_compliance_report_preserves_category(invoice):
    """
    Property 15: Compliance Report Structure (Category Preservation)
    
    For any compliance report, the 'category' field SHALL match the 
    category from the input invoice.
    
    Validates: Requirements 9.8, 9.5
    """
    # Mock environment variables
    with patch.dict(os.environ, {
        'GOOGLE_API_KEY': 'test-api-key',
        'CONVEX_URL': 'https://test.convex.cloud'
    }):
        # Mock ConvexClient
        with patch('app.compliance.ConvexClient') as mock_convex_class:
            mock_convex = MagicMock()
            mock_convex_class.return_value = mock_convex
            
            # Mock vector search results
            mock_convex.query.return_value = []
            
            # Mock Gemini API Client for embeddings
            with patch('app.rag_query.genai.Client') as mock_client_class:
                mock_client = MagicMock()
                mock_embed_result = Mock()
                mock_embed_result.embeddings = [Mock(values=[0.1] * 768)]
                mock_client.models.embed_content.return_value = mock_embed_result
                mock_client_class.return_value = mock_client
                
                # Create auditor and run audit
                auditor = ComplianceAuditor()
                report = auditor.audit_invoice(invoice)
    
    # Property: Category in report must match invoice category
    assert report["category"] == invoice.category.value, (
        f"Expected report category to match invoice category.\n"
        f"Invoice category: {invoice.category.value}\n"
        f"Report category: {report['category']}"
    )


# Feature: rag-compliance-engine, Property 15: Compliance Report Structure (Status Validity)
@given(invoice=invoice_strategy())
@settings(max_examples=100, deadline=None)
def test_compliance_report_has_valid_status(invoice):
    """
    Property 15: Compliance Report Structure (Status Validity)
    
    For any compliance report, the 'status' field SHALL be one of the 
    valid status values: "compliant", "review_needed", or "blocked".
    
    Validates: Requirements 9.8, 9.2
    """
    # Mock environment variables
    with patch.dict(os.environ, {
        'GOOGLE_API_KEY': 'test-api-key',
        'CONVEX_URL': 'https://test.convex.cloud'
    }):
        # Mock ConvexClient
        with patch('app.compliance.ConvexClient') as mock_convex_class:
            mock_convex = MagicMock()
            mock_convex_class.return_value = mock_convex
            
            # Mock vector search results
            mock_convex.query.return_value = []
            
            # Mock Gemini API Client for embeddings
            with patch('app.rag_query.genai.Client') as mock_client_class:
                mock_client = MagicMock()
                mock_embed_result = Mock()
                mock_embed_result.embeddings = [Mock(values=[0.1] * 768)]
                mock_client.models.embed_content.return_value = mock_embed_result
                mock_client_class.return_value = mock_client
                
                # Create auditor and run audit
                auditor = ComplianceAuditor()
                report = auditor.audit_invoice(invoice)
    
    # Property: Status must be one of the valid values
    valid_statuses = ["compliant", "review_needed", "blocked"]
    assert report["status"] in valid_statuses, (
        f"Expected report status to be one of {valid_statuses}.\n"
        f"Got: {report['status']}\n"
        f"Invoice: vendor={invoice.vendor_name}, amount={invoice.total_amount}"
    )


if __name__ == "__main__":
    # Run the tests manually
    import pytest
    pytest.main([__file__, "-v"])
